name: Test, Build and Publish

on:
  push:
    paths:
      - "src/yacs_stubgen/**"
      - "poetry.lock"
      - ".github/workflows/test-pub.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: poetry
      - run: |
          poetry install -n -vv
          poetry run python conf/default.py && [ -f conf/default.pyi ] && echo "✅"

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry and Publish to PyPI
        run: |
          pipx install poetry
          export POETRY_PYPI_TOKEN_PYPI=${{ secrets.PYPI_TOKEN }}
          poetry publish --build
